### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by niosus** [dnote-io/cli#6] opened 2017-04-05 07:27 UTC
This looks really interesting, but fails to install on my system.

Output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1341  100  1341    0     0   5728      0 --:--:-- --:--:-- --:--:--  5730
Download Dnote binary from curl https://github.com/dnote-io/cli/releases/download/v0.0.2/dnote-linux-amd64 to /usr/local/bin/dnote
Installation failed
```

Tell me how I can provide you with more info.

**Comment by juanjcsr** [comment] 2017-04-05 22:36
I think this happens because the `curl` command is trying to write to `/usr/local/bin/dnote` which in Ubuntu is restricted for the non root users. 

An easy fix could be to run the whole script with `sudo` however I don't think this is a great idea. Probably trying to create a file in that dir and if it fails, ask for sudo could be a better alternative?

**Comment by niosus** [comment] 2017-04-06 15:43
Actually, even when running with sudo rights did not work either.

**Comment by sungwoncho** [comment] 2017-04-07 10:20
I was able to reproduce it on Ubuntu 16.04. Will look into it.

**Comment by sungwoncho** [comment] 2017-04-07 10:36
The following worked for me (note `sudo` after the pipe rather than in front of `curl`):

    curl https://raw.githubusercontent.com/dnote-io/cli/master/install.sh | sudo sh

It turns out that we need to either add `sudo` or run `chown /usr/local` in this case.

Some ideas:

* specify the above solution in the README
* there might be a way to download the binary, and copy it to `/usr/local` using `sudo` inside [install.sh](https://github.com/dnote-io/cli/blob/master/install.sh).
* If download fails, suggest using `sudo`

How do you feel about these solutions?

**Comment by niosus** [comment] 2017-04-07 10:53
Ok, I feel stupid not to try sudo before the `sh` command. :)

As for the solution, the best one would be to ask the user for sudo password if needed in the process of running the script. I don't think asking users to put sudo in the middle of the command line is very user-friendly. At least maybe the script can be restructured in a way, that it starts with `sh`, so that `sudo` could go right before it in the beginning of the command line.

**Comment by sungwoncho** [comment] 2017-04-08 02:11
In that case, let's suppress the output for `curl` with `-s` flag. Updated the README.

    curl -s https://raw.githubusercontent.com/dnote-io/cli/master/install.sh | sudo sh

Yes, I agree that asking users to execute some shell script using `sudo` is not user-friendly.

Maybe install Dnote system-wide is unnecessary? Feedback welcomed. I will close this in the meantime. Please reopen if issue persists.

**Closed by sungwoncho** 2017-04-08 02:11 UTC
