### ISSUE TITLE
Edit and delete notes.

### ISSUE THREAD

**Issue by YiiKuoChong** [dnote-io/cli#15] opened 2017-04-11 12:25 UTC
There is a few features I think that could be a good addition to the program.

**BOOKS**
- Delete able books.

**NOTES**
- A identification system for notes
- Editable notes.
- Delete able notes.

I think this would create an easier and better user experience for programmers.
The way I think we should implement this is by having an identification system for notes (as suggested by Michiel) and use that to edit or delete notes, since books already have their own UID, it would ( I think ) be similar to deleting a note with slight modification.

p.s : I rewrote the issue.

**Comment by michielboekhoff** [comment] 2017-04-11 13:19
@sungwoncho This might be useful - editing a note for typos and such could come in handy. Deleting is a different matter. Of course, maybe a naming system would be required, as I'd prefer for users not to have to deal with the `UID` directly, as I believe this to be an implementation detail. What do you think?

**Comment by sungwoncho** [comment] 2017-04-13 11:41
Yes, UIDs are hard to remember, so I am open to the idea of adding names to notes. But I think a name should be optional so we can make notes quickly.

Here is what I am thinking:

    dnote new 'curl -s makes curl silent' # create note without title (auto-generate title)
    dnote new -t 'Silent Curl' 'curl -s makes curl silent' # create note with title
    dnote edit 'Silent Curl' (or UID) '-s flag suppresses curl output'
    dnote delete 'Silent Curl' (or UID)

A slight complication: do we allow duplicate names for notes? if there are duplicates, we might have to ask user for clarification on delete or edit. While it's too soon to worry about such case, I would like to get others feedback on this.

**Comment by YiiKuoChong** [comment] 2017-04-13 11:49
@sungwoncho  I submitted a pull request an hour or 2 ago, currently it forces the user to use names but I like your idea, I will see what I can do in the next few days. Currently, I am trying to implement a support for the new kind of file.

**Comment by YiiKuoChong** [comment] 2017-04-13 11:55
@sungwoncho About the complication stuff, I am thinking to append a number at the end of the note name so that every note would have unique names but of course the same name can be used across different books, just like how Microsoft implements their folder name system.

**Comment by YiiKuoChong** [comment] 2017-04-15 09:18
@sungwoncho  I have updated the code.

**Comment by sungwoncho** [comment] 2017-04-23 08:35
I have been reviewing PR from @YiiKuoChong and thinking about how I would use this new feature. Here are my thoughts:

* Dnote was designed to quickly write down what we learn with minimal context switching while coding. I don't see myself or users assigning names to our notes.
* Assigning names is unnecessarily complex. We need to
  - Ensure uniqueness
    - the current PR does not address this (having a predetermined format https://github.com/dnote-io/cli/pull/18/files#diff-cd575165f84eed10d10eb1460b0927b4R97 is not sufficient)
    - To ensure uniqueness we have to iterate over the whole notes in a book. Not efficient
  - Allow editing of names (the current PR does not address this.)

Instead of names, I propose that we use index of the note to refer to notes when editing/deleting.

    dnote edit [book name] [index] "[content]"
    dnote edit js 1 "blah blah"

We can obtain the index using `dnote notes`

    $ dnote notes
    In book JS:

    [0] - Blah blah
    [1] - Blah blah
    [2] - Blah blah
    [3] - Blah blah

By the way, I also open sourced the [web client](https://github.com/dnote-io/cli/pull/18/files#diff-52b1d24056db5a2ff73fadf4ecaace62R93). In the long run, the web client will help devs easily consume bite-sized lessons from other developers around the world (much like twitter but for devs). To keep things minimal and stick to 'microlessons,' I don't see having a title for a note fitting with this long term plan.

Any thoughts @YiiKuoChong @michielboekhoff

**Comment by michielboekhoff** [comment] 2017-04-23 09:16
I see your point, @sungwoncho. Maybe using indexes is a better way. 

Thanks for open sourcing the web client. I've just had a quick look, and it looks good! I work with React at my place of employment and I'll have a better look tomorrow. I hope that soon, the server might become OSS too. 

If necessary, @YiiKuoChong, I'll walk you through making the necessary changes to this PR.

**Comment by sungwoncho** [comment] 2017-04-23 09:24
@michielboekhoff Thanks for the feedback. The API and job server are already open sourced btw: https://github.com/dnote-io/api https://github.com/dnote-io/job

**Comment by YiiKuoChong** [comment] 2017-04-23 09:45
@sungwoncho My idea here is : 
1. Add a Index variable in the JSON file.
2. Add a function which list the notes in the book.

e.g
> ### Commandline
> dnote notes ( List all the notes in current book. )
> dnote notes -b "book_name" ( List all the notes in the specified book. )

> ### Output
> [ Index ] [ Note Name ]                        [ Content ]
>      1        book_note_001                      Note content 1.
>      2        book_note_002                      Note content 2.
>      3        book_note_003                      Note content 3.
>      4        book_note_004                      Note content 4.
>      5        book_note_005                      Note content 5.

The reason I proposed to keep the note name is that it would add another way for developers to find notes that they wants instead of reading the only the notes. It would be helpful if developers have a large note.

3. Add a function to make sure index is unique and does not repeat. 

If it does repeat, we take appropriate action to correct it. There would be multiple reason why note index would repeat, first is that the user themselves edited .dnote file. Another is there is a previous bug in the program (I will try my best to avoid this from happening by reviewing the code a few time before pushing them to GitHub ) .

@sungwoncho @michielboekhoff Do you think we should make sure that the index is the same as the amount of notes in a book? If so, we should : 

4. Add a function to rearrange the index.

What do you guys think?
I will start coding the solutions once we agree on what to do.

**Comment by YiiKuoChong** [comment] 2017-04-26 07:44
@sungwoncho utils.go is importing itself. Can you please fix it? I am not sure how to test the program with my own code while retaining GitHub link as the import.

**Comment by YiiKuoChong** [comment] 2017-04-26 11:31
I decided to remove the note name completely.

**Comment by sungwoncho** [comment] 2017-04-28 01:50
* I think the following features are not needed:

> 3. Add a function to make sure index is unique and does not repeat.
> 4. Add a function to rearrange the index.

The reason is that we can simply use indices from Go slice.

* Import was fixed by https://github.com/dnote-io/cli/pull/23.

> What is the JOB server for?

Job server is a program that sends out email digest every Fridays.

> if the code is not on the main branch, the program will not work

You should be able to compile and run the program even if you branch off. Let me know if you need help with that.

Merged https://github.com/dnote-io/cli/pull/26 and closing this.

**Closed by sungwoncho** 2017-04-28 01:50 UTC
